set gfn=Menlo\ Regular:h14
set antialias

set visualbell     " Don't beep

set gcr=n:blinkon0 " Don't blick the cursor

set guioptions-=T  " no toolbar
set guioptions=r   " no scrollbars
set fullscreen
