"" First, Pathogen to handle plugins
call pathogen#infect()

set nocompatible
set encoding=utf-8
set title                       " Set the terminal's title

"" Whitespace
set nowrap                      " don't wrap lines

" line at 80th character
set colorcolumn=80

" Theme
set background=dark
colorscheme Tomorrow-Night-Bright

" Remap esc. to the most useless key on a Mac keyboard
imap § <C-[>
cmap § <C-[>

set list " show <Tab> as ^I and end-of-line as $

" Filetypes
" Better git commit support
autocmd Filetype gitcommit setlocal spell textwidth=72
" bats is just bash
autocmd BufNewFile,BufRead *.bats set filetype=bash

" Plugins
" configure ctrlp
let g:ctrlp_working_path_mode = 2              " set the working dir at the nearest ancestor that contains .git
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*.so " ignore some files
let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files'] " use git to list files (faster)

" Enable global undo dir
set undofile
set undodir=~/.vim/undo/

" Relative line numbers
set relativenumber number
autocmd InsertEnter * set number norelativenumber
autocmd InsertLeave * set relativenumber number

" Not needed because of airline
set noshowmode
