set nocompatible

filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

Plugin 'tpope/vim-bundler'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-haml'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-sleuth'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'bling/vim-airline'
Plugin 'bronson/vim-trailing-whitespace'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'godlygeek/tabular'
Plugin 'kien/ctrlp.vim'
Plugin 'mhinz/vim-signify'
Plugin 'rking/ag.vim'
Plugin 'scrooloose/syntastic'
Plugin 'vim-ruby/vim-ruby'
Plugin 'zerowidth/vim-copy-as-rtf'
Plugin 'kchmck/vim-coffee-script'
Plugin 'vim-scripts/taglist.vim'
Plugin 'vim-scripts/lua.vim'
Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-lua-ftplugin'
Plugin 'twerth/ir_black'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

set encoding=utf-8
set title                       " Set the terminal's title

"" Whitespace
set nowrap                      " don't wrap lines

" line at 80th character
set colorcolumn=80

" Theme
set background=dark
colorscheme Tomorrow-Night-Bright

set list " show <Tab> as ^I and end-of-line as $

" Filetypes
" Better git commit support
autocmd Filetype gitcommit setlocal spell textwidth=72
" Enable spellcheck on markdown files
autocmd Filetype markdown setlocal spell
" bats is just bash
autocmd BufNewFile,BufRead *.bats set filetype=bash
" handlebars is just html
autocmd BufNewFile,BufRead *.hbs set filetype=html

" Plugins
" configure ctrlp
let g:ctrlp_working_path_mode = 2              " set the working dir at the nearest ancestor that contains .git
set wildignore+=*/.git/*,*/.hg/*,*/.svn/*,*.so " ignore some files
let g:ctrlp_user_command = ['.git/', 'cd %s && git ls-files'] " use git to list files (faster)

" Enable global undo dir
set undofile
set undodir=~/.vim/undo/

" Relative line numbers
set relativenumber number
autocmd InsertEnter * set number norelativenumber
autocmd InsertLeave * set relativenumber number

" Not needed because of airline
set noshowmode

" Dispatch
autocmd FileType ruby let b:dispatch = 'bundle exec rspec %'

map <Tab> :Rake<CR>
map § :Dispatch<CR>

" Automatically remove trailing-space
" autocmd BufWritePre * :%s/\s\+$//e

" Insert only one space when joining lines that contain sentence-terminating
" punctuation like `.`.
set nojoinspaces

" Sideways plugin
" nnoremap <c-h> :SidewaysLeft<cr>
" nnoremap <c-l> :SidewaysRight<cr>

" syntastic
" let g:syntastic_ruby_checkers = ['mri', 'rubocop']

" utf-8 list chars for tabs, trailing spaces
if !has('win32') && (&termencoding ==# 'utf-8' || &encoding ==# 'utf-8')
  let &listchars = "tab:\u21e5 ,trail:\u2423,extends:\u21c9,precedes:\u21c7,nbsp:\u00b7"
endif

" faster syntax highlighting
set regexpengine=1

let g:airline_powerline_fonts = 1
